# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GhaAnalyzer < Formula
  desc "Analyze GitHub Actions workflow runs to identify performance bottlenecks and flaky tests"
  homepage "https://github.com/stefanpenner/gha-analyzer"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stefanpenner/gha-analyzer/releases/download/v0.1.0/gha-analyzer_darwin_amd64.tar.gz"
      sha256 "074847f2ca76f83b6bb7ee1ac7f1922031be2bfc933c4e773cddd6eb1c8524b5"

      def install
        bin.install "gha-analyzer"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stefanpenner/gha-analyzer/releases/download/v0.1.0/gha-analyzer_darwin_arm64.tar.gz"
      sha256 "707a23d5e2a7ae74eef4c10c0afb1287083de83f13624c7389af5d08af248869"

      def install
        bin.install "gha-analyzer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/stefanpenner/gha-analyzer/releases/download/v0.1.0/gha-analyzer_linux_amd64.tar.gz"
      sha256 "991e7c3e4d77fb850dc4ab744b77b91bb4fa8a1f2c8dd53165719aa5eee1b573"
      def install
        bin.install "gha-analyzer"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stefanpenner/gha-analyzer/releases/download/v0.1.0/gha-analyzer_linux_arm64.tar.gz"
      sha256 "7e1c0acaf08a6d579bf0fc1f5926cc7e10567791906b745db9715116df4acc0a"
      def install
        bin.install "gha-analyzer"
      end
    end
  end

  test do
    system "#{bin}/gha-analyzer", "--help"
  end
end
