# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ote < Formula
  desc "Analyze OpenTelemetry traces to identify performance bottlenecks"
  homepage "https://github.com/stefanpenner/otel-explorer"
  version "0.11.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stefanpenner/otel-explorer/releases/download/v0.11.0/otel-explorer_darwin_amd64.tar.gz"
      sha256 "25c4c786d85637f15a02e44252f58e87fe694bd7f8d533dca56141a176918f5e"

      define_method(:install) do
        bin.install "ote"
        bin.install_symlink "ote" => "otel-explorer"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stefanpenner/otel-explorer/releases/download/v0.11.0/otel-explorer_darwin_arm64.tar.gz"
      sha256 "a0fc2481fc604c336414cd8585f07548e57028a96d8c8f844775afb3e753e8bc"

      define_method(:install) do
        bin.install "ote"
        bin.install_symlink "ote" => "otel-explorer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/stefanpenner/otel-explorer/releases/download/v0.11.0/otel-explorer_linux_amd64.tar.gz"
      sha256 "2495dfaf052822a21c0eb12b4bf190b98d945f81f6de5a4a0a27cd8c0c8d917a"
      define_method(:install) do
        bin.install "ote"
        bin.install_symlink "ote" => "otel-explorer"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stefanpenner/otel-explorer/releases/download/v0.11.0/otel-explorer_linux_arm64.tar.gz"
      sha256 "d3adabdcb997e29678f27ee139a607c9a376d7db94e590e611a9e5c95c664046"
      define_method(:install) do
        bin.install "ote"
        bin.install_symlink "ote" => "otel-explorer"
      end
    end
  end

  test do
    system "#{bin}/ote", "--help"
  end
end
