# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ote < Formula
  desc "Analyze OpenTelemetry traces to identify performance bottlenecks"
  homepage "https://github.com/stefanpenner/otel-explorer"
  version "0.13.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stefanpenner/otel-explorer/releases/download/v0.13.0/otel-explorer_darwin_amd64.tar.gz"
      sha256 "dc906f645fbf57c2d55c39310e0c3417d18ed65248ee866eaa8b4d272598ca82"

      define_method(:install) do
        bin.install "ote"
        bin.install_symlink "ote" => "otel-explorer"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stefanpenner/otel-explorer/releases/download/v0.13.0/otel-explorer_darwin_arm64.tar.gz"
      sha256 "eb7c3cbb70203c84fe3190308e41440003063c919dd5401018785875e5b73d05"

      define_method(:install) do
        bin.install "ote"
        bin.install_symlink "ote" => "otel-explorer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/stefanpenner/otel-explorer/releases/download/v0.13.0/otel-explorer_linux_amd64.tar.gz"
      sha256 "20e3e41b39ea77241d4562f957d2d99f6c7e17efcebf2ef05ab8da13f3696ae3"
      define_method(:install) do
        bin.install "ote"
        bin.install_symlink "ote" => "otel-explorer"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stefanpenner/otel-explorer/releases/download/v0.13.0/otel-explorer_linux_arm64.tar.gz"
      sha256 "93bca853fb5043770b037bb698b74b9e76c8d2ef7638b62b184425f626d34188"
      define_method(:install) do
        bin.install "ote"
        bin.install_symlink "ote" => "otel-explorer"
      end
    end
  end

  test do
    system "#{bin}/ote", "--help"
  end
end
