# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ote < Formula
  desc "Analyze OpenTelemetry traces to identify performance bottlenecks"
  homepage "https://github.com/stefanpenner/otel-explorer"
  version "0.12.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stefanpenner/otel-explorer/releases/download/v0.12.0/otel-explorer_darwin_amd64.tar.gz"
      sha256 "404c3346e0dd3d0932896fd6a4ed30830ba20e1c9f4b74bca7ee4f2216b3a511"

      define_method(:install) do
        bin.install "ote"
        bin.install_symlink "ote" => "otel-explorer"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stefanpenner/otel-explorer/releases/download/v0.12.0/otel-explorer_darwin_arm64.tar.gz"
      sha256 "0063e7e32e5f7ca5534b1042db256d0d413788424e53a320f7cc6e737856e0f5"

      define_method(:install) do
        bin.install "ote"
        bin.install_symlink "ote" => "otel-explorer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/stefanpenner/otel-explorer/releases/download/v0.12.0/otel-explorer_linux_amd64.tar.gz"
      sha256 "007fff0ec0be5cb302ff8b3d243d102fb2631b248d2da5dae2e58858d2ab5745"
      define_method(:install) do
        bin.install "ote"
        bin.install_symlink "ote" => "otel-explorer"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stefanpenner/otel-explorer/releases/download/v0.12.0/otel-explorer_linux_arm64.tar.gz"
      sha256 "3f70358eb687fa604880fdfcda9c429c092bc26e6f9e9afa940d97cb9d1d205a"
      define_method(:install) do
        bin.install "ote"
        bin.install_symlink "ote" => "otel-explorer"
      end
    end
  end

  test do
    system "#{bin}/ote", "--help"
  end
end
