# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OtelExplorer < Formula
  desc "Analyze OpenTelemetry traces to identify performance bottlenecks"
  homepage "https://github.com/stefanpenner/otel-explorer"
  version "0.4.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stefanpenner/otel-explorer/releases/download/v0.4.0/otel-explorer_darwin_amd64.tar.gz"
      sha256 "e1b56761946c4b7fe87cfd48395de40d0dd78311d0b971cb64945466063d17ea"

      define_method(:install) do
        bin.install "otel-explorer"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stefanpenner/otel-explorer/releases/download/v0.4.0/otel-explorer_darwin_arm64.tar.gz"
      sha256 "eacb52e1f0091b311a481499feb1befb19f6d69a092adaaf057abae52df5a0b2"

      define_method(:install) do
        bin.install "otel-explorer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/stefanpenner/otel-explorer/releases/download/v0.4.0/otel-explorer_linux_amd64.tar.gz"
      sha256 "df42e433a3f795d9b215e0c871126583f10afff75d6d699fbad098166bd8d698"
      define_method(:install) do
        bin.install "otel-explorer"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stefanpenner/otel-explorer/releases/download/v0.4.0/otel-explorer_linux_arm64.tar.gz"
      sha256 "5fc0c2d6f076b7c2cf7d8e34745137414b39262f54d9b9ad63d66f05e6c8e7ee"
      define_method(:install) do
        bin.install "otel-explorer"
      end
    end
  end

  test do
    system "#{bin}/otel-explorer", "--help"
  end
end
