# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OtelAnalyzer < Formula
  desc "Analyze OpenTelemetry traces to identify performance bottlenecks"
  homepage "https://github.com/stefanpenner/otel-analyzer"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stefanpenner/otel-analyzer/releases/download/v0.2.0/otel-analyzer_darwin_amd64.tar.gz"
      sha256 "f644907aa2c06d2a36564e69e2f9aee40c81d13200b81e28525cfc763cc0de99"

      define_method(:install) do
        bin.install "otel-analyzer"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stefanpenner/otel-analyzer/releases/download/v0.2.0/otel-analyzer_darwin_arm64.tar.gz"
      sha256 "013f88a2e1d1060aa7f42be6e2792cd7889db58f88eab9422d97c78ef6aa4047"

      define_method(:install) do
        bin.install "otel-analyzer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/stefanpenner/otel-analyzer/releases/download/v0.2.0/otel-analyzer_linux_amd64.tar.gz"
      sha256 "c5ce67317e0026fc075662dd0ccf5ddacd103679ac4f32e6b80cd7d4bde665a1"
      define_method(:install) do
        bin.install "otel-analyzer"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stefanpenner/otel-analyzer/releases/download/v0.2.0/otel-analyzer_linux_arm64.tar.gz"
      sha256 "5b3359befefd736b19fd0e23b796d54a992aa89b84b2652581d0c5aea760e40d"
      define_method(:install) do
        bin.install "otel-analyzer"
      end
    end
  end

  test do
    system "#{bin}/otel-analyzer", "--help"
  end
end
