# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shh < Formula
  desc "Commit your secrets. Yes, really."
  homepage "https://github.com/stefanpenner/shh"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stefanpenner/shh/releases/download/v0.3.0/shh_darwin_amd64.tar.gz"
      sha256 "3beb2004cec77677838cf83d3d3ac3aa226e1a79602d9775386886d5debe26b5"

      define_method(:install) do
        bin.install "shh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stefanpenner/shh/releases/download/v0.3.0/shh_darwin_arm64.tar.gz"
      sha256 "27ae7e2935a3c1698ba83515e4390c36cc58cc09a0c932a21a8d7425e2861529"

      define_method(:install) do
        bin.install "shh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/stefanpenner/shh/releases/download/v0.3.0/shh_linux_amd64.tar.gz"
      sha256 "23c0eba168046868737fe076bbcda49dd51b27a0b0ee7a913f7aa23c19fbbee1"
      define_method(:install) do
        bin.install "shh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stefanpenner/shh/releases/download/v0.3.0/shh_linux_arm64.tar.gz"
      sha256 "b9cf3e219a1af8f49136e4a671a502fb9cf064fe2c58754f9cb0270337b72cbe"
      define_method(:install) do
        bin.install "shh"
      end
    end
  end
end
