# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shh < Formula
  desc "Commit your secrets. Yes, really."
  homepage "https://github.com/stefanpenner/shh"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stefanpenner/shh/releases/download/v0.2.0/shh_darwin_amd64.tar.gz"
      sha256 "b5ddb6a7ae289d180dcf2beb182e039dfbacf09843c351e0a843fa4f869f79f0"

      define_method(:install) do
        bin.install "shh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stefanpenner/shh/releases/download/v0.2.0/shh_darwin_arm64.tar.gz"
      sha256 "ebe67127a0557e3d670f90c613996e5be4699a06e3a9cd1535294e69ece2d8f6"

      define_method(:install) do
        bin.install "shh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/stefanpenner/shh/releases/download/v0.2.0/shh_linux_amd64.tar.gz"
      sha256 "452822f46fc6f9dd10e82c8c68a565ba3db7101490663c724196751ffcb534ea"
      define_method(:install) do
        bin.install "shh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stefanpenner/shh/releases/download/v0.2.0/shh_linux_arm64.tar.gz"
      sha256 "e5f6b582f12192e99189e1d45be14dbecca00ca17b3772860edb534e91bec4ab"
      define_method(:install) do
        bin.install "shh"
      end
    end
  end
end
